apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: pipeline-backend
description: main application pipeline
serialPipeline:
  stages:
  - targetId: run-staging
    profiles: [staging]
  - targetId: run-prod
    profiles: [prod]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-staging
description: Cloud Run Staging service
run:
  location: projects/tugas-akhir-10683/locations/asia-southeast2
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-prod
description: Cloud Run production service
requireApproval: true
run:
  location: projects/tugas-akhir-10683/locations/asia-southeast2